when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: restore-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:6a5cf9cf3813e9b5a554f56dbc9c073cb24463b7bddd5b10e25790d732e68938
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      restore: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache

  - name: go-test
    image: dhi.io/golang:1.26.5-debian13-dev@sha256:4f8306e798384952c56c754db2ef72f075413a73a0bcf512890fe43d58f315de
    environment:
      GOMODCACHE: /woodpecker/src/git.m0sh1.cc/m0sh1/netzbremse/.go-mod-cache
    commands:
      - mkdir -p .go-mod-cache
      - go test ./...

  - name: browser-script-check
    image: dhi.io/node:26.6.0-0-debian13-dev@sha256:6d6e098c424b244ca7f53d0f870a093c114d051e496b572030d84d16661d1983
    commands:
      - node --check scripts/netzbremse-browser.mjs

  - name: rebuild-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:6a5cf9cf3813e9b5a554f56dbc9c073cb24463b7bddd5b10e25790d732e68938
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      rebuild: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache
