when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: restore-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:fa8180c3ba7455577e00207d2d61e321be78987252c52c7d96437c8f3d14c911
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      restore: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache

  - name: go-test
    image: dhi.io/golang:1.27.1-debian13-dev@sha256:53279fba4fc5f47bcf7871c21e25aea629e90b987d4ae2d6c7186d266ef7c263
    environment:
      GOMODCACHE: /woodpecker/src/git.m0sh1.cc/m0sh1/netzbremse/.go-mod-cache
    commands:
      - mkdir -p .go-mod-cache
      - go test ./...

  - name: browser-script-check
    image: dhi.io/node:26.10.0-0-debian13-dev@sha256:698dc9ab7a5fa66ed0de16160befe400dcf902ee9c95c8f02c971ff2bd919815
    commands:
      - node --check scripts/netzbremse-browser.mjs

  - name: rebuild-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:fa8180c3ba7455577e00207d2d61e321be78987252c52c7d96437c8f3d14c911
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      rebuild: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache
